//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36245
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPatch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALTER FUNCTION [dbo].[fn_Get_MudVolMan_TotalVolOfDFS_ByReportIdAndDfs] (@curRepID" +
            " BigInt, @Dfs_AutoID INT, @ActLossFactor  DECIMAL(15, 5))\r\nRETURNS DECIMAL(15, 3" +
            ")\r\nAS\r\nBEGIN\r\n\t \r\n\tDECLARE @mudVolManDFSID BigInt;\r\n\t \r\n\tSELECT @mudVolManDFSID " +
            "= rmd.ID\r\n\tFROM rt_Rep2MudVolManDFS rmd \r\n\tWhere rmd.Dfs_AutoID = @Dfs_AutoID an" +
            "d rmd.ReportID = @curRepID\r\n\t---------------------------------------------------" +
            "------\r\n\tDECLARE @WellID BigInt;\r\n\r\n\tselect @WellID = rw.WellID\r\n\tfrom rt_Rig2We" +
            "ll rw join at_Report r on rw.ID = r.RigWellID\r\n\twhere r.ID = @curRepID\r\n\t-------" +
            "--------------------------\r\n\tDECLARE @RepNum Int;\r\n\r\n\tselect @RepNum = at_Report" +
            ".Num from  at_Report where ID = @curRepID\r\n\t---------------------------------\r\n\r" +
            "\n\tdeclare @availableVol as decimal(15, 5) = 0;\r\n\r\n\tSELECT @availableVol = sum(is" +
            "null(Volume, 0))\r\n\tFROM \r\n\t(\r\n\t\tSELECT  (t.Vol) AS Volume\r\n\t\tFROM rt_Rep2MudVolM" +
            "anDFS_RecTrans t\r\n\t\tWHERE t.RecTrans_Flag = 0 and t.MudVolManDFS_ID = @mudVolMan" +
            "DFSID\r\n\t\t\t\t\r\n\t\tUNION ALL -- including duplicates\r\n\r\n\t\tSELECT  -(t.Vol) AS Volume" +
            "\r\n\t\tFROM rt_Rep2MudVolManDFS_RecTrans t\r\n\t\tWHERE t.RecTrans_Flag = 1 and t.MudVo" +
            "lManDFS_ID = @mudVolManDFSID\r\n\r\n\t\tUNION ALL -- including duplicates\r\n\r\n\t\tSELECT " +
            "(BuiltRainVol + BuiltGainVol + BuiltStartVol) AS Volume\r\n\t\tFROM rt_Rep2MudVolMan" +
            "DFS  WHERE ID  = @mudVolManDFSID   \r\n\r\n\t\tUNION ALL -- including duplicates\r\n\r\n\t\t" +
            "SELECT (b.AddOil + b.AddSeaWater + b.AddDrillWater + b.AddLocalWater + b.AddDeWa" +
            "ter + dbo.fn_Get_BuiltPrd_ChemicalVolume(b.ID)) AS Volume\r\n\t\tFROM rt_Rep2MudVolM" +
            "anDFS_BuiltVol b\r\n\t\tWHERE b.MudVolManDFS_ID = @mudVolManDFSID \r\n\t\t\r\n\t\tUNION ALL " +
            "-- including duplicates\r\n\t\t\r\n\t\tSELECT (t.AddOil + t.AddSeaWater + t.AddDrillWate" +
            "r + t.AddLocalWater + t.AddDeWater + dbo.fn_Get_TreatedPrd_ChemicalVolume(t.ID))" +
            " AS Volume\r\n\t\tFROM rt_Rep2MudVolManDFS_TreatedVol t\r\n\t\tWHERE t.MudVolManDFS_ID =" +
            " @mudVolManDFSID\r\n\t\t\r\n\t\tUNION ALL -- including duplicates\r\n\t\t\r\n\t\tSELECT (u.UsedV" +
            "ol /*+ dbo.fn_Get_BuiltUsingPrd_ChemicalVolume(u.ID)*/) AS Volume\r\n\t\tFROM rt_Rep" +
            "2MudVolManDFS_BuiltUsingOthers u\r\n\t\tWHERE u.MudVolManDFS_ID = @mudVolManDFSID\r\n\r" +
            "\n\t\tUNION ALL -- including duplicates\r\n\r\n\t\t--Used for others\r\n\t\tSELECT -(u.UsedVo" +
            "l) AS Volume\r\n\t\tFROM rt_Rep2MudVolManDFS_BuiltUsingOthers u\r\n\t\tjoin rt_Rep2MudVo" +
            "lManDFS rmd on u.MudVolManDFS_ID = rmd.ID\r\n\t\tWHERE  rmd.ReportID = @curRepID and" +
            " rmd.Dfs_AutoID <> @Dfs_AutoID and u.Dfs_AutoID = @Dfs_AutoID\r\n\r\n\t\tUNION ALL -- " +
            "including duplicates\r\n\r\n\t\t------------LOSSES--------------\r\n\t\tselect -(Vol) from" +
            " rt_Rep2MudLossRecord where ReportID = @curRepID and Dfs_AutoID = @Dfs_AutoID\r\n\t" +
            "\t\r\n\t\tUNION ALL -- including duplicates\r\n\t\t\r\n\t\tselect -(Vol) from rt_Rep2MudLossF" +
            "ormation where ReportID = @curRepID and Dfs_AutoID = @Dfs_AutoID\r\n\t\t\r\n\t\tUNION AL" +
            "L -- including duplicates\r\n\t\t\r\n\t\tselect -(rscu.Used*rscu.Discharge*@ActLossFacto" +
            "r) \r\n\t\tfrom rt_Rep2SolidControl rsc join rt_Rep2SolidControlUsed rscu on rsc.ID " +
            "= rscu.R2SC_ID \r\n\t\twhere rsc.ReportID = @curRepID and rscu.Dfs_AutoID = @Dfs_Aut" +
            "oID\r\n\r\n\t\tUNION ALL -- including duplicates\r\n\r\n\t\tselect -(AtEndMudRetWasteVol+AtE" +
            "ndMudRetOverVol+DailyMudRetWasteVol+DailyMudRetOverVol) /*+ DailyMudRetPitVol + " +
            "AtEndMudRetPitVol - DailyStringDisp - AtEndMudDispVol*/\r\n\t\tfrom  rt_Rep2MudVolMa" +
            "nDFS where ID = @mudVolManDFSID\r\n\r\n\t\tUNION ALL -- including duplicates\r\n\r\n\t\tsele" +
            "ct - dbo.fn_Get_AfterMergeVol_ByWellID_UptoRepNum(@WellID, @RepNum, @Dfs_AutoID)" +
            " AS Volume\r\n\r\n\t) as temp\r\n\t-----------------------------------------------------" +
            "----\r\n\tRETURN @availableVol;\r\n\t-------------------------------------------------" +
            "--------\r\nEND")]
        public string FixQuery {
            get {
                return ((string)(this["FixQuery"]));
            }
            set {
                this["FixQuery"] = value;
            }
        }
    }
}
